//! `jev-ask`: file a question, answer it once, and hold the queue until it is answered.
//!
//! # The two ways this is used
//!
//! An **agent** files a question instead of asking it in the transcript, because prose in a
//! stream is unrecoverable by construction:
//!
//! ```text
//! jev-ask ask "which front end produced this build?" \
//!     --option "the Vite app in cocoteams-ng" --option "the bridge in coco-connect" \
//!     --default "the Vite app in cocoteams-ng" \
//!     --blocks "reproduce the rendering bug" --expires-in 48
//! ```
//!
//! A **person** answers from one screen, and never types an id if they do not want to:
//!
//! ```text
//! jev-ask open            # what is waiting on me, ranked by what it holds up
//! jev-ask answer 1        # take the recommendation  (this is the fast path)
//! jev-ask answer 1 "the bridge in coco-connect" --note "the Vite app is a mock"
//! ```
//!
//! # The gate
//!
//! `jev-ask gate` exits 2 when something is holding the queue, and prints what. That is the
//! rule that stops a queued prompt from being injected past an unanswered decision: the queue
//! is generated by a step that will not emit blocked work, so auto-injection stops being the
//! enemy because nothing injectable is blocked.
//!
//! # Exit codes
//!
//! `0` fine, `1` an error (bad input, a damaged log), `2` the gate is held. Deliberately not
//! "1 for everything": a caller has to be able to tell "you cannot proceed" from "I broke".

use std::path::PathBuf;
use std::process::Command;

use jev_ask::{
    blocking, due_for_expiry, human_age, lane_of, new_id, now, open_now, resolve_id, summarize,
    Event, IdError, Question, State, Store,
};

/// The most rows `open` shows before it says how many it hid.
///
/// Seven, because a list you cannot finish in one glance becomes another thing to avoid, and
/// the whole point is that this one gets finished.
const SHOWN: usize = 7;

fn main() {
    std::process::exit(run());
}

fn run() -> i32 {
    let args: Vec<String> = std::env::args().skip(1).collect();
    let store = Store::from_env();
    let verb = args.first().map(String::as_str).unwrap_or("help");

    let result = match verb {
        "ask" => cmd_ask(&store, &args[1..]),
        "open" | "list" | "answers" => cmd_open(&store, &args[1..]),
        "answer" | "a" => cmd_answer(&store, &args[1..]),
        "gate" => cmd_gate(&store, &args[1..]),
        "sweep" => cmd_sweep(&store, &args[1..]),
        "stats" => cmd_stats(&store, &args[1..]),
        "show" => cmd_show(&store, &args[1..]),
        "cancel" => cmd_cancel(&store, &args[1..]),
        "help" | "--help" | "-h" => {
            usage(&store);
            0
        }
        other => {
            eprintln!("jev-ask: unknown command {other:?}");
            usage(&store);
            1
        }
    };
    result
}

/// Read one value for a `--flag`.
fn flag(args: &[String], name: &str) -> Option<String> {
    let mut it = args.iter();
    while let Some(a) = it.next() {
        if a == name {
            return it.next().cloned();
        }
        if let Some(rest) = a.strip_prefix(&format!("{name}=")) {
            return Some(rest.to_string());
        }
    }
    None
}

/// Read every value for a repeatable `--flag`.
fn flag_all(args: &[String], name: &str) -> Vec<String> {
    let mut out = Vec::new();
    let mut it = args.iter();
    while let Some(a) = it.next() {
        if a == name {
            if let Some(v) = it.next() {
                out.push(v.clone());
            }
        } else if let Some(rest) = a.strip_prefix(&format!("{name}=")) {
            out.push(rest.to_string());
        }
    }
    out
}

/// The positional arguments, with flags and their values removed.
fn positional(args: &[String]) -> Vec<String> {
    let mut out = Vec::new();
    let mut it = args.iter().peekable();
    while let Some(a) = it.next() {
        if a.starts_with("--") {
            let inline = a.contains('=');
            if !inline && it.peek().map(|n| !n.starts_with("--")).unwrap_or(false) {
                it.next();
            }
            continue;
        }
        out.push(a.clone());
    }
    out
}

/// Which project we are standing in, when we are standing in one.
///
/// `None` when the cwd is not inside a git repository, and that distinction matters: a
/// `gate` run from `/tmp` must not invent a lane called `tmp` and report "clear", because a
/// false clear is the exact failure this tool exists to prevent. Without a repo, the gate
/// looks at every lane instead.
fn current_lane() -> Option<String> {
    Command::new("git")
        .args(["rev-parse", "--show-toplevel"])
        .output()
        .ok()
        .filter(|o| o.status.success())
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
        .filter(|s| !s.is_empty())
        .map(|top| lane_of(&PathBuf::from(top)))
}

/// A lane to file under: the repository if there is one, else the directory we are in.
fn lane_for_asking() -> String {
    current_lane()
        .or_else(|| std::env::current_dir().ok().map(|d| lane_of(&d)))
        .unwrap_or_else(|| "unknown".to_string())
}

fn usage(store: &Store) {
    println!("jev-ask - questions that wait for you instead of scrolling away");
    println!();
    println!("  ask <question> --option A --option B [--default A] [--blocks WHAT]");
    println!("                 [--lane L] [--expires-in HOURS] [--by WHO] [--json]");
    println!("  open [--lane L] [--all] [--json]     what is waiting on you, ranked");
    println!("  answer <id|#N> [choice] [--note ...] omit the choice to take the default");
    println!("  gate [--lane L]                      exit 2 while something holds the queue");
    println!("  sweep                                apply defaults whose clock ran out");
    println!("  stats                                asked / open / answered / expired");
    println!("  show <id>                            one question in full");
    println!("  cancel <id> --reason ...             it stopped mattering");
    println!();
    println!("  log  {}", store.path().display());
    println!("  override it with JEV_DECISIONS");
}

fn cmd_ask(store: &Store, args: &[String]) -> i32 {
    let pos = positional(args);
    let Some(text) = pos.first() else {
        eprintln!("jev-ask ask: needs a question. See `jev-ask help`.");
        return 1;
    };
    let mut options = flag_all(args, "--option");
    options.retain(|o| !o.trim().is_empty());
    if options.is_empty() {
        eprintln!("jev-ask ask: needs at least one --option.");
        eprintln!(
            "  A question without a closed set of answers cannot be answered in a keystroke,"
        );
        eprintln!("  which is the only reason this exists. Offer the two or three real choices.");
        return 1;
    }
    let default = flag(args, "--default").unwrap_or_else(|| options[0].clone());
    if !options.contains(&default) {
        eprintln!("jev-ask ask: --default {default:?} is not one of the options.");
        eprintln!("  options: {}", options.join(" | "));
        return 1;
    }
    let lane = flag(args, "--lane").unwrap_or_else(lane_for_asking);
    let by = flag(args, "--by").unwrap_or_else(|| "agent".to_string());
    let blocks = flag_all(args, "--blocks");
    let t = now();
    let expires_at = flag(args, "--expires-in")
        .and_then(|h| h.parse::<u64>().ok())
        .filter(|h| *h > 0)
        .map(|h| t + h * 3600);

    let id = new_id(t, text);
    let event = Event::Asked {
        id: id.clone(),
        at: t,
        lane: lane.clone(),
        text: text.clone(),
        options: options.clone(),
        default: default.clone(),
        blocks: blocks.clone(),
        asked_by: by,
        expires_at,
    };
    if let Err(e) = store.append(&event) {
        eprintln!(
            "jev-ask: could not write to {}: {e}",
            store.path().display()
        );
        return 1;
    }

    if flag(args, "--json").is_some() {
        println!(
            "{{\"id\":{:?},\"lane\":{:?},\"default\":{:?},\"blocks\":{:?}}}",
            id, lane, default, blocks
        );
        return 0;
    }
    println!("{id}  asked in {lane}");
    println!("  {}", text);
    println!("  options: {}", options.join(" | "));
    match expires_at {
        Some(e) => println!(
            "  unanswered for {} it becomes: {default}",
            human_age(e - t)
        ),
        None => println!("  unanswered it waits forever, and never applies itself"),
    }
    if blocks.is_empty() {
        println!("  note: filed without --blocks, so this does NOT hold the queue.");
        println!("        If work is waiting on it, say so: --blocks \"what is waiting\"");
    } else {
        println!("  holding: {}", blocks.join(", "));
    }
    println!("  answer it with: jev-ask answer {id}");
    0
}

fn describe(q: &Question, n: usize, t: u64) -> String {
    let held = if q.blocks.is_empty() {
        String::new()
    } else {
        format!("  HOLDS {}", q.blocks.join(", "))
    };
    let clock = match q.expires_in(t) {
        Some(s) if s > 0 => format!("expires in {}", human_age(s as u64)),
        Some(_) => "overdue: sweep will apply the default".to_string(),
        None => "no expiry".to_string(),
    };
    format!(
        "[{n}] {}  {}  {}{}\n     {}\n     options: {}   default: {}\n     {}",
        q.id,
        q.lane,
        human_age(q.age(t)),
        held,
        q.text,
        q.options.join(" | "),
        q.default,
        clock
    )
}

fn cmd_open(store: &Store, args: &[String]) -> i32 {
    let t = now();
    let qs = match store.questions() {
        Ok(q) => q,
        Err(e) => {
            eprintln!("jev-ask: cannot read {}: {e}", store.path().display());
            return 1;
        }
    };
    let lane = flag(args, "--lane");
    let mut waiting = open_now(&qs, t);
    if let Some(l) = &lane {
        waiting.retain(|q| &q.lane == l);
    }
    let due = due_for_expiry(&qs, t);

    if flag(args, "--json").is_some() {
        let rows: Vec<String> = waiting
            .iter()
            .map(|q| {
                format!(
                    "{{\"id\":{:?},\"lane\":{:?},\"text\":{:?},\"options\":{:?},\"default\":{:?},\"blocks\":{:?},\"age\":{}}}",
                    q.id, q.lane, q.text, q.options, q.default, q.blocks, q.age(t)
                )
            })
            .collect();
        println!("[{}]", rows.join(","));
        return 0;
    }

    if waiting.is_empty() {
        println!("nothing is waiting on you.");
        if !due.is_empty() {
            println!("  {} overdue: run `jev-ask sweep`", due.len());
        }
        return 0;
    }

    let all = flag(args, "--all").is_some();
    let shown = if all { waiting.len() } else { SHOWN };
    println!("{} waiting on you:", waiting.len());
    println!();
    for (i, q) in waiting.iter().take(shown).enumerate() {
        println!("{}", describe(q, i + 1, t));
        println!();
    }
    if waiting.len() > shown {
        println!("... {} more (--all)", waiting.len() - shown);
    }
    println!("answer by row or id:  jev-ask answer 1        (takes the default)");
    println!(
        "                      jev-ask answer {} \"<one of the options>\"",
        waiting[0].id
    );
    0
}

fn cmd_answer(store: &Store, args: &[String]) -> i32 {
    let pos = positional(args);
    let Some(target) = pos.first() else {
        eprintln!("jev-ask answer: which one? `jev-ask open` first, or pass an id.");
        return 1;
    };
    let t = now();
    let qs = match store.questions() {
        Ok(q) => q,
        Err(e) => {
            eprintln!("jev-ask: cannot read {}: {e}", store.path().display());
            return 1;
        }
    };

    // `#3` means "the third row of the ranking as it stands now". The id is printed beside
    // every row, so a caller who wants certainty does not have to use this at all.
    let id = if let Some(n) = target.strip_prefix('#') {
        let idx: usize = match n.parse::<usize>() {
            Ok(i) if i > 0 => i - 1,
            _ => {
                eprintln!("jev-ask answer: {target:?} is not a row number. Use #1, #2, ...");
                return 1;
            }
        };
        match open_now(&qs, t).get(idx) {
            Some(q) => {
                println!("row #{} is {}", idx + 1, q.id);
                q.id.clone()
            }
            None => {
                eprintln!(
                    "jev-ask answer: there is no row #{}. `jev-ask open` shows the list.",
                    idx + 1
                );
                return 1;
            }
        }
    } else {
        match resolve_id(&qs, target) {
            Ok(id) => id,
            Err(IdError::NotFound(_)) => return answer_by_row_number(store, &qs, target, args, t),
            Err(e) => {
                eprintln!("jev-ask answer: {e}");
                return 1;
            }
        }
    };

    let q = match qs.iter().find(|q| q.id == id) {
        Some(q) => q,
        None => {
            eprintln!("jev-ask answer: {id} vanished from the log");
            return 1;
        }
    };
    if !matches!(q.state, State::Open) {
        eprintln!(
            "jev-ask answer: {id} is already {:?} (answered {:?})",
            q.state, q.answer
        );
        return 1;
    }

    let choice = match pos.get(1) {
        Some(c) => c.clone(),
        None => {
            println!("taking the default: {:?}", q.default);
            q.default.clone()
        }
    };
    if !q.options.contains(&choice) {
        eprintln!("jev-ask answer: {choice:?} is not one of the options for {id}.");
        eprintln!("  options: {}", q.options.join(" | "));
        eprintln!(
            "  Nothing was written. A choice outside the set is a new question, not an answer."
        );
        return 1;
    }

    let event = Event::Answered {
        id: id.clone(),
        at: t,
        answer: choice.clone(),
        by: flag(args, "--by").unwrap_or_else(|| "human".to_string()),
        note: flag(args, "--note"),
    };
    if let Err(e) = store.append(&event) {
        eprintln!("jev-ask: could not write: {e}");
        return 1;
    }
    println!("{id} -> {choice}");
    if let Some(n) = flag(args, "--note") {
        println!("  note for the agent: {n}");
    }
    if choice == q.default {
        println!("  (that was the recommendation)");
    }
    0
}

/// A bare number that is not an id is almost certainly a row number.
fn answer_by_row_number(
    store: &Store,
    qs: &[Question],
    target: &str,
    args: &[String],
    t: u64,
) -> i32 {
    if target.parse::<usize>().is_ok() {
        let mut forwarded = vec![format!("#{target}")];
        forwarded.extend(positional(args).into_iter().skip(1));
        for (i, a) in args.iter().enumerate() {
            if a.starts_with("--") {
                forwarded.push(a.clone());
                if let Some(v) = args.get(i + 1) {
                    if !v.starts_with("--") {
                        forwarded.push(v.clone());
                    }
                }
            }
        }
        let _ = qs;
        return cmd_answer(store, &forwarded);
    }
    eprintln!("jev-ask answer: no question matches {target:?}. `jev-ask open` shows the list.");
    let _ = t;
    1
}

fn cmd_gate(store: &Store, args: &[String]) -> i32 {
    let t = now();
    let qs = match store.questions() {
        Ok(q) => q,
        Err(e) => {
            eprintln!("jev-ask: cannot read the log: {e}");
            return 1;
        }
    };
    // No lane means "not inside a repository": check every lane rather than inventing one.
    let lane = flag(args, "--lane").or_else(current_lane);
    let held = blocking(&qs, lane.as_deref(), t);

    if held.is_empty() {
        let scope = lane.clone().unwrap_or_else(|| "every lane".to_string());
        let open_but_idle = open_now(&qs, t)
            .into_iter()
            .filter(|q| lane.as_ref().map(|l| &q.lane == l).unwrap_or(true))
            .filter(|q| !q.blocks_anything())
            .count();
        println!("queue clear for {scope}");
        if open_but_idle > 0 {
            println!(
                "  {open_but_idle} open question(s) that hold nothing up: they wait, work does not"
            );
        }
        return 0;
    }

    let scope = lane.clone().unwrap_or_else(|| "every lane".to_string());
    println!(
        "HELD: {} question(s) are blocking work in {scope}",
        held.len()
    );
    println!();
    for (i, q) in held.iter().enumerate() {
        println!("{}", describe(q, i + 1, t));
        println!();
    }
    println!("The queue does not advance past these. Answer with `jev-ask answer <row>`.");
    2
}

fn cmd_sweep(store: &Store, args: &[String]) -> i32 {
    let t = now();
    let qs = match store.questions() {
        Ok(q) => q,
        Err(e) => {
            eprintln!("jev-ask: cannot read the log: {e}");
            return 1;
        }
    };
    let due = due_for_expiry(&qs, t);
    if due.is_empty() {
        println!("nothing is overdue");
        return 0;
    }
    let dry = flag(args, "--dry-run").is_some();
    for q in &due {
        if dry {
            println!("would apply: {} -> {:?}", q.id, q.default);
            continue;
        }
        let event = Event::Expired {
            id: q.id.clone(),
            at: t,
            applied: q.default.clone(),
        };
        if let Err(e) = store.append(&event) {
            eprintln!("jev-ask: could not write the expiry for {}: {e}", q.id);
            return 1;
        }
        println!(
            "{}  nobody answered for {}  ->  applied {:?}   ({})",
            q.id,
            human_age(q.age(t)),
            q.default,
            q.text
        );
    }
    println!();
    println!(
        "{} question(s) resolved by default. Tell the asking agent; it did not choose this.",
        due.len()
    );
    0
}

fn cmd_stats(store: &Store, args: &[String]) -> i32 {
    let t = now();
    let qs = match store.questions() {
        Ok(q) => q,
        Err(e) => {
            eprintln!("jev-ask: cannot read {}: {e}", store.path().display());
            return 1;
        }
    };
    let s = summarize(&qs, t);
    let due = due_for_expiry(&qs, t);

    if flag(args, "--json").is_some() {
        println!(
            "{{\"asked\":{},\"open\":{},\"answered\":{},\"expired\":{},\"cancelled\":{},\"median_seconds\":{},\"took_default\":{}}}",
            s.asked,
            s.open,
            s.answered,
            s.expired,
            s.cancelled,
            s.median_time_to_answer.map(|v| v.to_string()).unwrap_or_else(|| "null".into()),
            s.took_default
        );
        return 0;
    }

    println!("log  {}", store.path().display());
    println!();
    println!(
        "asked {}   open {}   answered {}   expired {}   cancelled {}",
        s.asked, s.open, s.answered, s.expired, s.cancelled
    );
    match (s.median_time_to_answer, s.p90_time_to_answer) {
        (Some(m), Some(p)) => println!(
            "time to answer   median {}   p90 {}",
            human_age(m),
            human_age(p)
        ),
        _ => println!("time to answer   nothing resolved yet"),
    }
    let resolved = s.answered + s.expired;
    if resolved > 0 {
        println!(
            "took the default  {} of {} resolved ({}%)",
            s.took_default,
            resolved,
            100 * s.took_default / resolved
        );
    }
    if let Some(age) = s.oldest_open_age {
        println!("oldest open      {}", human_age(age));
    }
    if !s.per_lane.is_empty() {
        let lanes: Vec<String> = s.per_lane.iter().map(|(l, n)| format!("{l} {n}")).collect();
        println!("open by lane     {}", lanes.join(", "));
    }
    if !due.is_empty() {
        println!();
        println!(
            "{} overdue: `jev-ask sweep` applies their defaults",
            due.len()
        );
    }
    0
}

fn cmd_show(store: &Store, args: &[String]) -> i32 {
    let pos = positional(args);
    let Some(target) = pos.first() else {
        eprintln!("jev-ask show: needs an id");
        return 1;
    };
    let t = now();
    let qs = match store.questions() {
        Ok(q) => q,
        Err(e) => {
            eprintln!("jev-ask: cannot read the log: {e}");
            return 1;
        }
    };
    let id = match resolve_id(&qs, target) {
        Ok(id) => id,
        Err(e) => {
            eprintln!("jev-ask show: {e}");
            return 1;
        }
    };
    let q = match qs.iter().find(|q| q.id == id) {
        Some(q) => q,
        None => return 1,
    };
    println!("{}  {}", q.id, q.lane);
    println!("  asked      {} ago by {}", human_age(q.age(t)), q.asked_by);
    println!("  question   {}", q.text);
    println!("  options    {}", q.options.join(" | "));
    println!("  default    {}", q.default);
    if q.blocks.is_empty() {
        println!("  holds      nothing");
    } else {
        println!("  holds      {}", q.blocks.join(", "));
    }
    match q.expires_in(t) {
        Some(s) if s > 0 => println!("  expiry     in {}", human_age(s as u64)),
        Some(_) => println!("  expiry     overdue"),
        None => println!("  expiry     none"),
    }
    match q.state {
        State::Open => println!("  state      open"),
        other => println!(
            "  state      {:?} as {:?} after {}",
            other,
            q.answer.clone().unwrap_or_default(),
            q.resolved_at
                .map(|r| human_age(r.saturating_sub(q.asked_at)))
                .unwrap_or_default()
        ),
    }
    if let Some(n) = &q.note {
        println!("  note       {n}");
    }
    0
}

fn cmd_cancel(store: &Store, args: &[String]) -> i32 {
    let pos = positional(args);
    let Some(target) = pos.first() else {
        eprintln!("jev-ask cancel: needs an id");
        return 1;
    };
    let reason = flag(args, "--reason").unwrap_or_else(|| "no longer relevant".to_string());
    let t = now();
    let qs = match store.questions() {
        Ok(q) => q,
        Err(e) => {
            eprintln!("jev-ask: cannot read the log: {e}");
            return 1;
        }
    };
    let id = match resolve_id(&qs, target) {
        Ok(id) => id,
        Err(e) => {
            eprintln!("jev-ask cancel: {e}");
            return 1;
        }
    };
    let event = Event::Cancelled {
        id: id.clone(),
        at: t,
        reason: reason.clone(),
    };
    if let Err(e) = store.append(&event) {
        eprintln!("jev-ask: could not write: {e}");
        return 1;
    }
    println!("{id} cancelled: {reason}");
    0
}
